// <auto-generated />
using System;
using Covid19Survey.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Covid19Survey.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200726054655_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Covid19Survey.Models.UserResponse", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<bool?>("PublicTransportation")
                        .IsRequired();

                    b.Property<bool>("WearMask");

                    b.Property<bool?>("Work")
                        .IsRequired();

                    b.HasKey("Name");

                    b.ToTable("ResponseCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
